=== 13299118606/SeismicPackage/CPSeis/opencfe/etc/preferences.dtd
<!-- preferences.dtd -->

<!-- DTD for describing the preferences to be used by the client -->

<!-- The preferences element consists of: server name element, user name element 	-->
<!-- servlet name element and the XML document path element.						-->
<!ELEMENT Preferences 
	(ServerName, UserName, ScriptName, ServletName, XMLDocPath, BackEndLibPath, HelpMode, DefaultLabelFont?, DefaultFieldFont?, DefaultArrayFont?)>

<!-- Name of the server -->
<!ELEMENT ServerName (#PCDATA)>
	
<!-- Name of the user -->
<!ELEMENT UserName (#PCDATA)>
	
<!-- Name of the script -->
<!ELEMENT ScriptName (#PCDATA)>
	
<!-- Name of the servlet -->
<!ELEMENT ServletName (#PCDATA)>
	
<!-- Name of the xml document path -->
<!ELEMENT XMLDocPath (#PCDATA)>

<!-- The path for the backend libraries -->
<!ELEMENT BackEndLibPath (#PCDATA)>

<!ELEMENT HelpMode EMPTY>
<!ATTLIST HelpMode value (mouse | focus) "mouse">

<!-- Mode for Console -->

<!ELEMENT WithConsole EMPTY >
<!ATTLIST WithConsole value (yes | no) "yes">

<!ELEMENT DefaultLabelFont EMPTY>
<!ATTLIST DefaultLabelFont name CDATA #REQUIRED
                           style ( plain | italic | bold ) "plain"
                           size CDATA #REQUIRED>

<!ELEMENT DefaultFieldFont EMPTY>
<!ATTLIST DefaultFieldFont name CDATA #REQUIRED
                           style ( plain | italic | bold ) "plain"
                           size CDATA #REQUIRED>

<!ELEMENT DefaultArrayFont EMPTY>
<!ATTLIST DefaultArrayFont name CDATA #REQUIRED
                           style ( plain | italic | bold ) "plain"
                           size CDATA #REQUIRED>

=== 13299118606/SeismicPackage/CPSeis/opencfe/xml/prefs.xml
<?xml version="1.0"?>
<!DOCTYPE Preferences SYSTEM "http://poepsn05.po.conoco.com/Conoco/xml/preferences.dtd">
<Preferences>
	<ServerName>poepsn05.po.conoco.com</ServerName>
	<ScriptName>runrmi</ScriptName>
	<ServletName>http://poepsn05.po.conoco.com/servlets/com.conoco.cfe.servlet.MessagePasser</ServletName>
	<LoginServletName>http://poepsn05.po.conoco.com/servlets/com.conoco.cfe.servlet.LoginServlet</LoginServletName>
	<XMLDocPath>/Conoco/xml/</XMLDocPath>
	<BackEndLibPath>/usr/app/vendors/sps/lib/sparc-sun-solaris/libCFE.so</BackEndLibPath>
	<HelpMode value="mouse"/>
	<WithConsole value="no"/>
	<DefaultLabelFont name="SansSerif" size="14" />
	<DefaultFieldFont name="SansSerif" style="bold" size="14" />
	<DefaultArrayFont name="SansSerif" size="14" />
</Preferences>

=== 13299118606/SeismicPackage/CPSeis/opencfe/prefs.xml
<?xml version="1.0"?>
<!DOCTYPE Preferences SYSTEM "file:///home/mengewm/workspace/opencfe/etc/preferences.dtd">
<Preferences>
	<XMLDocPath>file:///home/mengewm/workspace/opencfe/xml/</XMLDocPath>
	<BackEndLibPath>/home/mengewm/workspace/cpseis/lib/linux32/libcps.so</BackEndLibPath>
	<HelpMode value="mouse"/>
	<WithConsole value="yes"/>
	<DefaultLabelFont name="SansSerif" size="14" />
	<DefaultFieldFont name="SansSerif" style="bold" size="14" />
	<DefaultArrayFont name="SansSerif" size="14" />
</Preferences>
